export const siteConfig = {
  description:
    "I'm a DWCK that got FWCK by the dev! The community took over so now we are one BIG QWCKing family.. I look at the sky every night and have always dreamed of flying. Help me reach my dream! You will find that someday I will fly and it may be too late.",
  keywords: [
    "jccdev",
    "Jordan Cruz-Correa",
    "software engineer",
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "TailwindCSS",
    "shadcn-ui",
    "full-stack developer",
    "frontend developer",
    "web development",
    "UI/UX design",
    "responsive design",
    "Windows 98 inspired",
    "retro tech",
    "portfolio",
    "Supabase",
    "Node.js",
    "PostgreSQL",
    "Git",
    "GitHub",
    "Vercel",
    "Netlify",
  ],
  creator: "DWCK",
  author: "DWCK",
  openGraph: {
    title: "DWCK FWCKs",
    description:
      "I'm a DWCK that got FWCK by the dev! The community took over so now we are one BIG QWCKing family.. I look at the sky every night and have always dreamed of flying. Help me reach my dream! You will find that someday I will fly and it may be too late.",
    url: "https://www.dwck.art/",
    siteName: "DWCK FWCKs",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "DWCK",
    description:
      "I'm a DWCK that got FWCK by the dev! The community took over so now we are one BIG QWCKing family.. I look at the sky every night and have always dreamed of flying. Help me reach my dream! You will find that someday I will fly and it may be too late.",
    creator: "@itsadwck",
    images: [
      "https://pbs.twimg.com/profile_banners/1861846689197211648/1732768088/1080x360",
    ],
  },
}
